### ISSUE TITLE
Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by TheAifam5** [kasecato/vscode-docomment#67]
The same error but other package: https://github.com/christophschlosser/doxdocgen/issues/79

Log:
```
[2018-06-26 22:27:54.566] [renderer1] [error] Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
    at DocommentDomainCSharp.IsTriggerDocomment (C:\Users\MateuszPaluszkiewicz\.vscode\extensions\k--kato.docomment-0.1.0\out\src\Domain\Lang\DocommentDomainCSharp.js:21:38)
    at DocommentDomainCSharp.Execute (C:\Users\MateuszPaluszkiewicz\.vscode\extensions\k--kato.docomment-0.1.0\out\src\Domain\DocommentDomain.js:20:19)
    at DocommentControllerCSharp._onEvent (C:\Users\MateuszPaluszkiewicz\.vscode\extensions\k--kato.docomment-0.1.0\out\src\Controller\DocommentController.js:52:31)
    at DocommentControllerCSharp.DocommentController.vscode_1.workspace.onDidChangeTextDocument.event (C:\Users\MateuszPaluszkiewicz\.vscode\extensions\k--kato.docomment-0.1.0\out\src\Controller\DocommentController.js:18:22)
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:784)
    at e.$acceptDirtyStateChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:685:973)
    at e.$acceptModelSaved (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:685:723)
    at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
    at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
    at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by kasecato** [comment]
@TheAifam5 Thank you for reporting!

```js
[2018-06-26 22:27:54.566] [renderer1] [error] Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
at Pipe.onread (net.js:560:20)
```
It does not trigger on `net.js`. This detects [TextDocumentContentChangeEvent.text](https://code.visualstudio.com/docs/extensionAPI/vscode-api#TextDocumentContentChangeEvent) only in `*.cs`.
