### ISSUE TITLE
Not working on Windows 10?

### ISSUE THREAD

**Issue by kasecato** [kasecato/vscode-docomment#99]
## Description
- Some reviewers have said it won't work on Windows 10.
- See [reviews](https://marketplace.visualstudio.com/items?itemName=k--kato.docomment&ssr=false#review-details)
<img width="1211" alt="Screen Shot 2020-07-21 at 21 06 26" src="https://user-images.githubusercontent.com/10364603/88052984-1240f000-cb96-11ea-9208-2dd40698861f.png">

## Try
- I checked the operation on Windows 10 using Virtual Box on macOS, and it worked fine 🤔
  - Windows 10 Enterprise Edition 64bit Version 1809
  - Visual Studio Code, Ver.1.47.2
  - C# XML Documentation Comments, Ver.0.1.14
  - C#, Ver.1.12.1

![win_docomment_0 1 14](https://user-images.githubusercontent.com/10364603/88053556-f427bf80-cb96-11ea-931a-6740bc016e3c.gif)

**Comment by xtr33me** [comment]
I am using Windows 10 and VSCode along with Unity 3D. When I get a little time I will come back to this to hopefully provide some more info.  I however did just install this plugin and it is causing a whole series of errors across a number of classes.  Some being Oculus specific and others in other packages/classes. I did notice some of the classes it finds when I have an error are sealed. Not sure yet if that is causing any issues, but again I will try to come back to this to provide some more info.

**Comment by xtr33me** [comment]
So I am currently trying to use this extension in VSCode 1.50.0 and this is associated to a Unity 3D project (not that it matters). I just got a new computer so it still has Windows Home on it.

![image](https://user-images.githubusercontent.com/1653419/96009954-44699300-0e0f-11eb-82bc-ec2b9c2f2e43.png)

To explain what I'm seeing, when I try to add the triple slashes above anything other than a property or a delegate, it seems to always just add:
```
/// <summary>
/// 
/// </summary>
```

When commenting above a property, it does however seem to pull the proper commenting template from the settings.json. I will tend to get the below error messages in dev tools whenever I click my cursor above the class, struct, etc.

![image](https://user-images.githubusercontent.com/1653419/96009511-bab9c580-0e0e-11eb-8416-7bfddf41eac1.png)

```
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'text' of undefined
	at DocommentDomainCSharp.IsTriggerDocomment (c:\Users\wna_b\.vscode\extensions\k--kato.docomment-0.1.18\out\src\Domain\Lang\DocommentDomainCSharp.js:30:39)
	at DocommentDomainCSharp.Execute (c:\Users\wna_b\.vscode\extensions\k--kato.docomment-0.1.18\out\src\Domain\DocommentDomain.js:23:19)
	at DocommentControllerCSharp._onEvent (c:\Users\wna_b\.vscode\extensions\k--kato.docomment-0.1.18\out\src\Controller\DocommentController.js:55:16)
	at DocommentControllerCSharp.<anonymous> (c:\Users\wna_b\.vscode\extensions\k--kato.docomment-0.1.18\out\src\Controller\DocommentController.js:18:22)
	at l.fire (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:821)
	at t.ExtHostDocuments.$acceptDirtyStateChanged (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:715:433)
	at m._doInvokeHandler (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:870:464)
	at m._invokeHandler (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:870:156)
	at m._receiveRequest (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:868:817)
	at m._receiveOneMessage (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:867:623)
	at c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:865:691
	at l.fire (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at v.fire (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:1059:179
	at l.fire (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at v.fire (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:256:381)
	at t.PersistentProtocol._receiveMessage (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:261:451)
	at c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:258:489
	at l.fire (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:45:801)
	at p.acceptChunk (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:851)
	at c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:253:203
	at Socket.t (c:\Users\wna_b\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:263:54)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
```

Hope that provides some more detailed info on the issue.
